name = "cloud"
description = "Commands for publishing applications to the Fermyon Cloud."
version = "0.10.0"
spin_compatibility = ">=1.3"
license = "Apache-2.0"
homepage = "https://github.com/fermyon/cloud-plugin"
package = "./target/release/cloud-plugin"
